baseURL = "http://getbytecode.org/"
languageCode = "en-us"
title = "GetByteCode"
# We disable taxonomies because we don't provide templates for them, and they
# don't apply to our minimal use case.
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  Subtitle = "Disassembler"
  About = "Welcome to Rubybytes, a disassembler for your ruby code.  Inspired by a project by Matt Godbold called <a href='https://github.com/mattgodbolt/gcc-explorer'>GCC Explorer</a> and aimed at Ruby from a suggestion by <a href='http://patshaughnessy.net/'>Pat Shaughnessy</a>."
  AboutSubline = "Made with loving care by <a href='http://twitter.com/jonnyman9'>Jon Keam</a>."
  GithubLink = "<a class='github' href='https://github.com/jkeam/rubybytes'><img class='github' style='position: absolute; top: 0; right: 0; border: 0;' src='https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67' alt='Fork me on GitHub' data-canonical-src='https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png'></a>"
